### ISSUE TITLE
Standard-based support of @context combination

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus-prov#11]
The workbench supports @context combination in a non [standard](https://www.w3.org/TR/json-ld/) way. 
Currently a @context to be combined looks like (http://contextToBeCombined.json):

```json
{
  "bcv": "{{base}}/voc/bbp/core/"
}
```

and it is combined like this:

```json
"@context": [
    "http://contextToBeCombined.json",
    {
      "this": "{{base}}/schemas/bbp/core/entity/v0.1.0/shapes/"
    }
  ]
```

The right syntax for contextToBeCombined.json is:

```json
{
 "@context": {
   "bcv": "{{base}}/voc/bbp/core/"
  }
}
```

The @context key is mandatory.

**Comment by MFSY** [comment]
@context objects needs to be well formed so that they can be stored and reused in nexus-kg or in json-ld aware clients

**Comment by bogdanromanx** [comment]
That was a little unintuitive... but the recommendation does state that imported contexts must be described as json objects with an `"@context"` field; any other fields are to be ignored along with any `"@base"` definitions.
